service: serverless-training

frameworkVersion: ">=2.0.0 <3.0.0"

provider:
  name: aws
  runtime: python3.8
  profile: celidor
  region: eu-west-1

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
